/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marnikitta_janet_tuntap_TunTap */

#ifndef _Included_marnikitta_janet_tuntap_TunTap
#define _Included_marnikitta_janet_tuntap_TunTap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marnikitta_janet_tuntap_TunTap
 * Method:    initTap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_marnikitta_janet_tuntap_TunTap_initTap
  (JNIEnv *, jclass);

/*
 * Class:     marnikitta_janet_tuntap_TunTap
 * Method:    initTun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_marnikitta_janet_tuntap_TunTap_initTun
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
